### ISSUE TITLE
Cannot run in gradle multiproject: Could not find method rewrite() for arguments [org.openrewrite.recipe:rewrite-micronaut:1.3.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

### ISSUE THREAD

**Issue by abcfy2** [openrewrite/rewrite#1263]
Hi there. I try to use micronaut in gradle multiproject. But I get this error:

```
Build file '/home/fengyu/下载/demo/app/build.gradle' line: 30

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method rewrite() for arguments [org.openrewrite.recipe:rewrite-micronaut:1.3.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
```

Here is the reproduce steps:

```sh
curl --location --request GET 'https://launch.micronaut.io/create/default/com.example.app?lang=JAVA&build=GRADLE&test=SPOCK&javaVersion=JDK_11&features=openrewrite' --output app.zip
mkdir -p demo
unzip -d demo app.zip
echo "include 'app'" > demo/settings.gradle
rm -f demo/app/settings.gradle
cd demo/app
./gradlew rewriteDryRun
```

Will show error;

```
* Where:
Build file '/home/fengyu/下载/demo/app/build.gradle' line: 30

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method rewrite() for arguments [org.openrewrite.recipe:rewrite-micronaut:1.3.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```

**Comment by lenaschimmel** [comment]
I experienced the same problem in my own project (coincidentially, also a micronaut project, though I think none of the problems is micronaut-specific), and could also reproduce it by following your steps. I will try to describe a solution.

[Step 2 of the Quickstart guide](https://docs.openrewrite.org/getting-started/getting-started#step-2-apply-rewrite-maven-plugin-or-rewrite-gradle-plugin) states:

> The Gradle plugin can only be applied to the root project. The tasks on the root project will orchestrate running recipes on all subprojects.

The OpenRewrite Guide does not explain how to do this, but some information can be found in [the Gradle guide](https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl).

You need to have a `build.gradle` file in your root project (`demo/build.gradle`):

```
plugins {
    id("java")

    // apply only to the root project
    id("org.openrewrite.rewrite") version("5.14.0")
}

repositories {
    // The root project doesn't have to be a Java project, but this is necessary
    // to resolve recipe artifacts.
    mavenCentral()
}

dependencies {
    rewrite("org.openrewrite.recipe:rewrite-micronaut:1.3.0")
} 

rewrite {
    activeRecipe("org.openrewrite.java.micronaut.Micronaut2to3Migration")
}
```

Then you can remove everything rewrite-related from your subproject file `demo/app/build.gradle`. Theoretically, you can also keep those lines there, but you need to change `id("org.openrewrite.rewrite") version("5.14.0")` to just `id("org.openrewrite.rewrite")` then, or you will get the error:

> Plugin request for plugin already on the classpath must not include a version

If you use JDK >= 16, you may now run into #909 which has [a workaround](https://github.com/openrewrite/rewrite/issues/909#issuecomment-902176202).

Also, you need to run your task from the root directory `demo`, not from `demo/app`. In your case, gradle wrapper is only presend in the `app` directory, so instead of `./gradlew rewriteDryRun` you must use `gradle rewriteDryRun` or initialize the wrapper in the root as well.

---

To get to this point, I made all the mistakes you made, and many more. I think the documentation should be improved, meaning both the [OpenRewrite Quickstart guide](https://docs.openrewrite.org/getting-started/getting-started#step-2-apply-rewrite-maven-plugin-or-rewrite-gradle-plugin) and the [Micronaut upgrade guide](https://docs.micronaut.io/latest/guide/#upgrading).

**Comment by abcfy2** [comment]
Great. It's working now. Thanks.

**Comment by sambsnyd** [comment]
Good feedback @abcfy2 @lenaschimmel. I'll improve the documentation in both of those places. And some time soon we will have better support for JDK 16+

**Comment by sambsnyd** [comment]
[I've added](https://github.com/openrewrite/rewrite-docs/commit/fbbfd7adba01d7f825c50ce385618cfef2334312) the --add-exports workaround to the micronaut docs page and increased the prominence of the instructions on the getting started page. 

Thanks again for letting us know about this.

**Comment by lenaschimmel** [comment]
Thank you for the quick reaction!

I just noticed a lot of missing spaces in your commit in the JVM options, before the `--add-exports` parameters. I made a [single-line-comment](https://github.com/openrewrite/rewrite-docs/commit/fbbfd7adba01d7f825c50ce385618cfef2334312#r61549276) but then realized that all four examples are affected (and were affected even before the commit).

**Comment by aegershman** [comment]
Just to follow-up, fixed the missing spaces and applied the feedback:
- https://github.com/openrewrite/rewrite-docs/commit/4586d1f0d8d11310621647ee17b33754182a13c1
- https://github.com/openrewrite/rewrite-docs/commit/5521f60d67d36cf8a70e512d10fbd92c5b2aaa64

Good catches, thank you 👍
