### ISSUE TITLE
Ensure ChangeType is updating method invocation type information

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite#1326]
ChangeType appears not to be updating the type info of method invocations to the new target class.

>Right now method invocation types aren't being updated by ChangeType.visitMethodInvocation() because it calls super.visitMethodInvocation() which calls this:
```
m = m.withMethodType((JavaType.Method) visitType(m.getMethodType(), p));
```
>But since ChangeType doesn't have an override for visitType() the method type is unchanged

(I don't have a demonstrable unit test at the moment.)

**Comment by sambsnyd** [comment]
I've verified that `ChangeType` is correctly updating method invocation type information. 

I remember when we first encountered this issue it was about a week before the issue got filed. At that time `TypeMapping` was significantly less correct than it is now, so I think the problem was actually there and has already been fixed.
