### ISSUE TITLE
Parsing Xml comment in 7.17.0 has a breaking change

### ISSUE THREAD

**Issue by honnix** [openrewrite/rewrite#1336]
Maybe it was an intended breaking change, so just ask here to confirm.

https://github.com/openrewrite/rewrite/commit/1616f9c89658fdcc79e96538d568637455951ff6 parses Xml comment as a real element. So in the following screenshot we have `content[4]` as `Xml$Comment` and `content[5].prefix` as `\n `.

<img width="1675" alt="Screenshot 2022-01-20 at 16 03 22" src="https://user-images.githubusercontent.com/158892/150364922-f64628c8-194c-445c-bbfc-51b5f11dad08.png">

When parsing the same file under 7.16.3, we got the following, with `content[4]` as `null` and `content[5].prefix` as the comment.

<img width="1463" alt="Screenshot 2022-01-20 at 15 52 02" src="https://user-images.githubusercontent.com/158892/150365220-b67c23b4-690c-4e69-b11f-f8a27b764ed1.png">

This feels like a valid change, however it does break how later on an element shall be transformed. Under 7.16.3, we could take the whole element with its comment, process it and output with comment untouched; under 7.17.1, we are not able to do this anymore because the element contains no comment so we will need to output the comment element explicitly.

**Comment by pway99** [comment]
Thanks @honnix, we'll have a look

**Comment by traceyyoshima** [comment]
Hi @honnix, you’re correct this is a valid change, which, unfortunately, adds complexity to your recipe. We plan to improve the user experience of handling XML comments.

At this time, we’re busy with re-working `Maven` resolution, so we’ll add it to our backlog and get back to it as soon as possible.

**Comment by honnix** [comment]
@pway99 @traceyyoshima That sounds good. Thanks for looking into this and replying. I think for now we can stay on 7.16.x for a little longer.

**Comment by honnix** [comment]
BTW, what do you think marking this as a breaking change in release notes? Although it's a minor version bump that is fine to have breaking changes, marking it explicitly could help folks when they upgrade.

**Comment by traceyyoshima** [comment]
@honnix Adding a section for breaking changes may be misleading since it may not cover each recipe. A lot changes as we move forward, and I am happy to help to adopt new releases.

So that you know, an `Xml.Comment` already existed as a part of the AST. Unintentionally, parsing did not transform comments within an `Xml.Content`.

Previously, XML comments would either exist as a part of the AST, in a `Xml.Tag.prefix` or `Xml.Tag.beforeTagDelimiterPrefix`, or become null.

Example:
```xml
<!-- `Tag.prefix` -->
<tag_start>
    <inner_tag_start>
        <!-- before non-tag content became null --> some tag text
    </inner_tag_end>
<!-- `Tag.beforeTagDelimiterPrefix` -->
</tag_end>
<!-- end of file became null -->
```
In general, I’ve found that comments are contextual to the user and circumstance. A `comment` may be associated with the previous element, the next element, code commented out, etc. So, it’s challenging to implement a behavior that fits everyone’s expectations without leaving it up to the user.

An example of ordering an `Xml.Tag` with the previous comments is the [OrderPomElements](https://github.com/openrewrite/rewrite/blob/main/rewrite-maven/src/main/java/org/openrewrite/maven/OrderPomElements.java#L84) recipe. However, we’re in the process of re-working `Maven` resolution, and it is subject to change.

I appreciate your feedback, opening an issue, and patience as an early adopter! I’d be happy to hop in a zoom through the OpenRewrite slack if you’d like support adopting 7.17. Thanks again!

**Comment by honnix** [comment]
@traceyyoshima Yeah, what you explained makes perfect sense. Thanks for the detailed information. I will talk to my team to see if we have an immediate need to upgrade to 7.17. We generally tend to keep dependencies up to date, so I see it should be happening soon if not immediately.

Please feel free to close or keep the issue, whichever fits your process better. Thanks again for the quick response!

**Comment by traceyyoshima** [comment]
@honnix happy to help!

Closing issue
