### ISSUE TITLE
Problems with "ChangeType" recipe with nested classes.

### ISSUE THREAD

**Issue by josemariavillar** [openrewrite/rewrite#1366]
Good morning, 

I am having problems when using the "ChangeType" recipe with nested classes. In my case, I have:

```
import es.old.example.AsyncProperties;

public String getExample(AsyncProperties properties) {
   return properties.getValue()
}
```
, and I use the recipe:

```
- org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: es.old.example.AsyncProperties
      newFullyQualifiedTypeName: es.new.example.Properties.Async
```

The expected result should be:

```
import es.new.example.Properties.Async;

public String getExample(Properties.Async properties) {
   return properties.getValue()
}
```

But I get the following:

```
public String getExample(Async properties) {
   return properties.getValue()
}
```

As you can see the "import" disappears and does not change the method property reference correctly.

**Comment by pway99** [comment]
Thanks @josemariavillar we'll have a look

**Comment by pway99** [comment]
Hi @josemariavillar,  It turns out this is not a bug after all.  
Here are some things to know about using `ChangeType` with Nested classes.

 - The`newFullyQualifiedTypeName` must use the _OuterClass$NestedClass_ naming convention,
     e.g. `es.new.example.Properties$Async`.
 - the parent class will be added to the `imports`
 - Type identifiers for the changed type are referenced from their parent class,
     e.g. `getExample(Properties.Async properties)`

Thus the transformation is as follows:

before:
```java
import es.old.example.AsyncProperties;

public String getExample(AsyncProperties properties) {
   return properties.getValue()
}
```

recipe:
```yaml
- org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: es.old.example.AsyncProperties
      newFullyQualifiedTypeName: es.new.example.Properties$Async
```

after:
```java
import es.new.example.Properties;

public String getExample(Properties.Async properties) {
   return properties.getValue()
}
```
