### ISSUE TITLE
Recipes for maven wrapper

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#1565]
It would be nice to have recipes for 

1. Add maven wrapper
2. Update maven wrapper to a specific version
     

Note : 

- `distributionUrl` and `wrapperUrl`  should be customizable for corporate environments

See : https://maven.apache.org/wrapper/

**Comment by yeikel** [comment]
@tkvangorder Should we create separate issues for this?

**Comment by tkvangorder** [comment]
I think this work will be similar to https://github.com/openrewrite/rewrite/issues/1542

I would suggest that the takari/maven-wrapper migration be made a separate task.

**Comment by yeikel** [comment]
> I think this work will be similar to #1542
> 
> I would suggest that the takari/maven-wrapper migration be made a separate task.

Thank you. I created https://github.com/openrewrite/rewrite/issues/1566

**Comment by yeikel** [comment]
I tested this internally and maven was smart enough to figure out the `distributionUrl` from my maven settings.

**Comment by timtebeek** [comment]
Would be good to also clean up [MavenWrapperDownloader.java](https://github.com/openrewrite/rewrite-maven-plugin/blob/main/.mvn/wrapper/MavenWrapperDownloader.java), as that get's left over otherwise.

**Comment by timtebeek** [comment]
Had a quick look through [the Apache Maven Wrapper Mojo](https://github.com/apache/maven-wrapper/blob/master/maven-wrapper-plugin/src/main/java/org/apache/maven/plugins/wrapper/WrapperMojo.java#L136) for inspiration, as that already downloads, unpacks & replaces properties, in addition to removing Takari wrapper files.

Would you recon we can declare a dependency on `org.apache.maven.plugins:maven-wrapper-plugin` and write a recipe that invokes `WrapperMojo#execute()`? There's some stuff to figure out still then like the `@Parameter/@Inject` annotated fields, but it might be preferable to reuse as much as possible.

Otherwise we can copy the ~200 or so lines in `WrapperMojo`, and only depend on `org.apache.maven.plugins:maven-wrapper` as a next best option.

What are your thoughts on the above? While the Apache Maven Wrapper plugin works as is, it would be nice to apply this in bulk through OpenRewrite, especially when it's a necessary step for other migration recipes such as a [Java 17 migration](https://github.com/openrewrite/rewrite-migrate-java/issues/109).

**Comment by yeikel** [comment]
As part of this recipe, we should make the wrapper executable: 

```shell
 chmod +x mvnw
```

Otherwise, some CI environments (like GH actions), will throw this: 

`./mvnw: Permission denied`

We can use `org.openrewrite.SetFilePermissions` for this
