### ISSUE TITLE
generic recipe to change method call

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#1719]
Given the following : 

````java

class A { 

@Deprecated
void method(int param1)

void method(int param1,int param2)

}

````

Is there any recipe that could help me to replace the usages of `method(int param1)` with `method(int param1,int param2)` or do we need a new recipe? 

`param2` is constant and I would be providing it

**Comment by traceyyoshima** [comment]
Hi @yeikel , an example of migrating a method invocation may be found here [rewrite-migrate-java](https://github.com/openrewrite/rewrite-migrate-java/blob/main/src/main/java/org/openrewrite/java/migrate/apache/commons/io/ApacheFileUtilsToJavaFiles.java).

I think we don't have a generalized recipe yet, because it may require constructing imports or type stubs for the JavaTemplate, etc.

I.E. someMethod(int a) => someMethod(NewObject b).
`NewObject` may not exist on the classpath, and may require a type stub, or could exist on the classpath like `java.util.List` and require an import.

**Comment by pway99** [comment]
Thanks @traceyyoshima, You are correct that there are cases (most often migrations) where the new argument type may not be on the classpath; however, it's also quite possible that classpath issues may not be a concern.  If the argument type is a parameter to the recipe, then it should be possible to add the import if necessary.

**Comment by yeikel** [comment]
In my concrete example, my parameter is a primitive but I understand your concerns

**Comment by timtebeek** [comment]
We now have two recipes in this space:
- https://docs.openrewrite.org/recipes/java/addliteralmethodargument
- https://docs.openrewrite.org/recipes/java/addnullmethodargument

With that I think we can close this issue; thanks again for the suggestion!
