### ISSUE TITLE
RemoveUnusedImports removes used imports on Apache James

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite#1798]
Running this recipe on https://github.com/apache/james-project results in a lot of used imported removed.

It seems to be a different case from #1698 since james-project is a multi-module maven.

![image](https://user-images.githubusercontent.com/155828/168447696-0f98a45b-1325-4ed3-a07f-a33a4283d8ea.png)

![image](https://user-images.githubusercontent.com/155828/168447779-eddf31ae-a935-4fa4-91d2-19c320271175.png)

**Comment by traceyyoshima** [comment]
Hi @murdos, thank you for reporting the issue, I'm taking a look!

**Comment by traceyyoshima** [comment]
@murdos I spent some time attempting to reproduce the issue on a clone of the project from the main branch, but am seeing a different issue. Are you running from a fork by chance?

**Comment by murdos** [comment]
@traceyyoshima : Thanks! You can try from this branch: https://github.com/murdos/james-project/tree/rewrite-playground
I had to disable maven parsing because I was having an issue while parsing dependencies.

**Comment by traceyyoshima** [comment]
> I had to disable maven parsing because I was having an issue while parsing dependencies.

Thank you for the branch, I see the issue you're referring to!

The removed imports are caused by the same line of code, `sourcePackage.equals(elem.getPackageName())`. But you're right, we can add an additional check to make sure a static inner class isn't being imported as well.

I'll put a fix together momentarily, thanks again!
