### ISSUE TITLE
Community request recipe: Add comments to an XML file based on an `xPath`.

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite#1817]
This is an issue based on user requests, based on #1802.

The recipe will be a variation of https://github.com/openrewrite/rewrite/pull/1809/files that uses an XmlVisitor and only contains an `xPath`.

**Comment by murdos** [comment]
Thanks! For the record my comment was more a suggestion on what recipe should be in rewrite repo vs in community or custom code. 
I had the feeling that AddCommentToMavenDependency was not generic enough and thus not really reusable. Why not then add AddCommentToMavenPlugin, AddCommentToMavenProperty, AddCommentToMavenProfile, ...?
That's why I was suggesting a more generic recipe like AddCommentToXmlTag that could serve to add comment to all elements of a Maven POM, but also serves more use cases.
