### ISSUE TITLE
Allow MethodMatcher type to be composed of multiple MethodMatcher

### ISSUE THREAD

**Issue by JLLeitschuh** [openrewrite/rewrite#1876]
Currently `MethodMatcher` can't match multiple methods. It would be convinient if you could build a method matcher that matches on multiple methods.

For example:

```java
MethodMatcher multiMatcher = MethodMatcher.from(
	MethodMacher.of("java.io.File <constructor>(java.io.File, java.lang.String)"),
	MethodMacher.of("java.io.File <constructor>(java.lang.String, java.lang.String)")
);
```

Or, as another example, if you wanted to match on two different `startsWith` on different types:

```java
MethodMatcher multiMatcher = MethodMatcher.from(
	MethodMacher.of("java.lang.String startsWith(..)"),
	MethodMacher.of("java.nio.file.Path startsWith(..)")
);
```

This could be easily be done if `MethodMatcher` were to be converted to an interface instead of a class and `MethodMatcher` had static factory methods exposed instead.

This would also follow Effective Java Item 1: [Consider static factory methods instead of constructors](https://www.baeldung.com/java-constructors-vs-static-factory-methods) as it would allow the underlying implementation of `MethodMatcher` to shift under users of the API without them needing to know how `MethodMatcher` is actually implemented.

**Comment by traceyyoshima** [comment]
Hi @JLLeitschuh, in the context of a recipe, a distinct match is very important because the matcher identifies a specific tree in the AST. The identification of a specific tree allows an author to safely make transformations. So most cases, I suspect these changes are not desired, but I'm curious about the application of multiple matches.

What is it that you're attempting to do? And why is it that something like the following example wouldn't work for you?

I.E.
```java
MethodMatcher stringStartsWith = new MethodMatcher("...");
MethodMatcher pathStartsWith = new MethodMatcher("...");

private boolean matchesStartsWith(ArgType argName) {
    return stringStartsWith.matches(argName) || pathStartsWith.matches(argName);
}
```

**Comment by traceyyoshima** [comment]
@JLLeitschuh, thanks for reporting the request! From what I understand, this has been discussed with @pway99 and is not necessary. Closing the issue due to inactivity.
