### ISSUE TITLE
Add Annotation Feature

### ISSUE THREAD

**Issue by jdelobel** [openrewrite/rewrite#1948]
Hi,

I want to create a recipe to add an Annotation for some existing classes. 

I need to add  @Component annotation.

Do you have an exemple please?

**Comment by jdelobel** [comment]
Hi @pway99 ,

Thanks for your reply. 

I am able to generate the @Component annotation!

My next problem is to add the import even using `maybeAddImport()` method.

Example: 

`

public class AddAnnotationVisitor extends JavaIsoVisitor<ExecutionContext> {

    private final String importComponent = "org.springframework.stereotype.Component";
    private final JavaTemplate componentAnnotationTemplate =
            JavaTemplate.builder(this::getCursor, "@Component").imports(importComponent)
                    .build();

    private final String fullyQualifiedClassName;

    public AddAnnotationVisitor(String fullyQualifiedClassName) {
        this.fullyQualifiedClassName = fullyQualifiedClassName;
    }

    @Override
    public J.ClassDeclaration visitClassDeclaration(J.ClassDeclaration classDecl, ExecutionContext executionContext) {


        // In any visit() method the call to super() is what causes sub-elements of to be visited
        J.ClassDeclaration cd = super.visitClassDeclaration(classDecl, executionContext);

        if (classDecl.getType() == null || !classDecl.getType().getFullyQualifiedName().equals(fullyQualifiedClassName)) {
            // We aren't looking at the specified class so return without making any modifications
            return cd;
        }

        if (cd.getAllAnnotations().stream().noneMatch(new AnnotationMatcher("@Component")::matches)
        ) {


            maybeAddImport(importComponent);
            cd = cd.withTemplate(componentAnnotationTemplate,
                    cd.getCoordinates().addAnnotation(Comparator.comparing(J.Annotation::getSimpleName))); //Annotation is added but not the import

        }
        return cd;
    }
}
`

Do you have any idea to add the corresponding import?

PS: I will come to your slack channel ASAP!

Thanks!

**Comment by pway99** [comment]
Hi @jdelobel,  Nice job getting your recipe working! 

Its most likely that your `@Component` annotation was generated without type information.   That happens when the JavaTemplat's JavaParser does not have an associated symbol.  Here are a few examples of how to configure the JavaParser with either a stub if the type is not on the class path or by setting the classpath when the type is available:

https://github.com/openrewrite/rewrite-spring/blob/eaaa54b7568316827d5d7ffaa412f1c319b98551/src/main/java/org/openrewrite/java/spring/boot2/WebSecurityConfigurerAdapterRecipe.java#L152-L158

https://github.com/openrewrite/rewrite-spring/blob/9cdd1f544dc2a4dc1485555f39e76470d82f21d2/src/testWithSpringBoot_1_5/kotlin/org/openrewrite/java/spring/boot2/RestTemplateBuilderRequestFactoryTest.kt#L24-L27

Here is some more info on the java template:
https://docs.openrewrite.org/v1beta/javatemplate

Also check out [TypeUtils](https://github.com/openrewrite/rewrite/blob/9f6ad318b6dcac700a36a4e4c6c72833253ffcce/rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java#L140) for comparing types
this:
```java
classDecl.getType() == null || !classDecl.getType().getFullyQualifiedName().equals(fullyQualifiedClassName)
```
can be replaced with this:
```java
TypeUtils.isOfClassType(classDecl.getType, fullyQualifiedClassName)
```

I will be out for a few weeks, the others on the team will be glad to help in the meantime :)

**Comment by jdelobel** [comment]
Thanks for you help @pway99 . Its working!

Now i just have to add deps and next steps :)

**Comment by traceyyoshima** [comment]
Hi @jdelobe, based on https://github.com/openrewrite/rewrite/issues/1976, I'm guessing this issue has been resolved for you, but I don't want to assume anything. Has your issue with adding annotations resolved?

**Comment by jdelobel** [comment]
> Hi @jdelobe, based on #1976, I'm guessing this issue has been resolved for you, but I don't want to assume anything. Has your issue with adding annotations resolved?

Hi @traceyyoshima : Its not the same problem. This issue is resolved. For the #1976  i have a problem to add the PARAMETER import
