### ISSUE TITLE
HCL Parser is confused with comment lines that contain curly braces

### ISSUE THREAD

**Issue by rmadamanchi** [openrewrite/rewrite#2079]
Below is a test case that demonstrates this issue: Notice the curly braces within the comment lines

```kotlin
import org.junit.jupiter.api.Test
import org.openrewrite.InMemoryExecutionContext
import org.openrewrite.hcl.HclParser
import org.openrewrite.hcl.tree.Hcl.ConfigFile
import kotlin.test.assertEquals


class ParserTest {
    @Test
    fun test() {
        val parser = HclParser.builder().build()

        val source = """
            locals {
                foo 
                myvar = {
                  # below {attributes}
                  myattribute = "myvalue"
                  
                  # add more attributes {here}
                }
            }
        """.trimIndent()
        val sources = parser.parse(InMemoryExecutionContext(), source)
        assertEquals(source, (sources[0] as ConfigFile).printAll())
    }
}
```
The reprinted content loses the comment and changes the indentation of the trailing curly brace.

```hcl
locals {
    foo = {}
    myvar = {
      # below {attributes}
      myattribute = "myvalue"
      
      }
}
```

**Comment by mccartney** [comment]
The `foo` line in the input seems like a typo? It doesn't look like valid HCL. I guess `foo = {}` was meant.

**Comment by mccartney** [comment]
Note after spending some time debugging it. Part of the problem seems this:
https://github.com/openrewrite/rewrite/blob/5198c78df0870c27087bf0d90835cf1953f2ed1e/rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/HclParserVisitor.java#L437
Particularly the `sourceBefore("}")` which kicks into the comments (while it shouldn't).

**Comment by mccartney** [comment]
And the problem is likely in this line:
https://github.com/openrewrite/rewrite/blob/5198c78df0870c27087bf0d90835cf1953f2ed1e/rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/HclParserVisitor.java#L728
as it takes `substring(, +2)` and compares it to a single-character String, which has no chance to succeed.

That also explains the mystery - why the original problem wouldn't happen if `//` comments are used and happens for `#`-style comments.
