### ISSUE TITLE
Should the JavaTemplate support replacing a single Annotation with multiple

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite#2327]
example of using ListUtils for replacing a single annotion with multiple.
```java
return classDecl.withLeadingAnnotations(ListUtils.flatMap(classDecl.getLeadingAnnotations(), ann -> {
                    String code = "@Suite\n@SelectClasspathResource(\"#{}\")";
                    String path = classDecl.getType().getPackageName().replace('.', '/');
                    JavaTemplate template = JavaTemplate.builder(this::getCursor, code)
                            .javaParser(
                                    () -> JavaParser.fromJavaVersion().classpath("junit-platform-suite-api").build())
                            .imports(SUITE, SELECT_CLASSPATH_RESOURCE)
                            .build();
                    List<J.Annotation> list = ann.withTemplate(template, ann.getCoordinates().replace(), path);
                    return list;
                }));
```
JavaTemplate code where all but the first generated annotation are ignored
https://github.com/openrewrite/rewrite/blob/63b7b972e7fa673fa1557bbdd4ecf46e577eda79/rewrite-java/src/main/java/org/openrewrite/java/JavaTemplate.java#L104-L116

cc: @timtebeek 
https://github.com/openrewrite/rewrite-testing-frameworks/pull/268

**Comment by timtebeek** [comment]
Just to give some more context on where this request was coming from:
In Cucumber-JVM we suggest users replace one custom annotation with two JUnit annotations, [as shown in the test](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/test/java/org/openrewrite/java/testing/cucumber/CucumberAnnotationToSuiteTest.java#L40).
In the workaround implementation we currently [add the annotations separately](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/java/org/openrewrite/java/testing/cucumber/CucumberAnnotationToSuite.java#L85), but earlier attempts had used something similar to the example above. (Perhaps using `JavaVisitor` instead of `JavaIsoVisitor`.)
In my earlier implementation attempt I'd seen some other cases where `withTemplate` would accept a list of statements, so I was mostly wondering why that did not work for annotations.

In practice workarounds are possible of course, but it's worth reconsidering (and/or documenting) this restriction with annotations.

**Comment by pway99** [comment]
Thanks Tim,
well this is embarrassing the example I provided above is totally incorrect (visit annotation returning a list) and would never work  :grimacing: 

I have updated the description with a snippet of your original code using ListUtils#flatMap, which is a reasonable approach to consider.  

I have been curious about this approach as well hence creating this issue as an opportunity investigate

**Comment by traceyyoshima** [comment]
> Just to give some more context on where this request was coming from: In Cucumber-JVM we suggest users replace one custom annotation with two JUnit annotations, [as shown in the test](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/test/java/org/openrewrite/java/testing/cucumber/CucumberAnnotationToSuiteTest.java#L40). In the workaround implementation we currently [add the annotations separately](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/java/org/openrewrite/java/testing/cucumber/CucumberAnnotationToSuite.java#L85), but earlier attempts had used something similar to the example above. (Perhaps using `JavaVisitor` instead of `JavaIsoVisitor`.) In my earlier implementation attempt I'd seen some other cases where `withTemplate` would accept a list of statements, so I was mostly wondering why that did not work for annotations.
> 
> In practice workarounds are possible of course, but it's worth reconsidering (and/or documenting) this restriction with annotations.

Hi @timtebeek !
Thank you for the context - I think adding the annotations separately is the right solution. :)

For context:
The differences between a list of statements and a list of annotations are related to the model objects that are based on the Java compiler.

A `J.ClassDeclaration` body is a `J.Block`, which contains a `List<Statement>`. The `J.Block` creates a `visitBlock` in the `JavaVisitor` which provides more flexibility. I.E. c.withBody(c.getBody().withStatements(...)).

A `J.Annotation` is contained in a `List` as a member in applicable `J` types. In this case, the `J.Annotation` is visited with visitAnnotation in `JavaVisitor`, which is called when a `J` uses `ListUtils.map(x.getLeadingAnnotations(), ...)` on it's member `leadingAnnotations`.

I may be overlooking a detail, but the example that @pway99 provided contains `List<J.Annotation> list = ann.withTemplate(template, ann.getCoordinates().replace(), path);` which conflicts with the API since the expectation is the method will return a single `J`. So, I suspect the suggested change would require something like a `J.Annotations`, which would wrap the `J.Annotation` and require a significant engineering effort. If `J.Annotations` is required then many of the `J` model objects would not mirror the Javac model objects anymore.

Additionally, `J.Annotations` may affect things like the prefix of the applicable `J` tree. It's subtle, but things like the whitespace, annotations, comments, or modifiers are adjusted during autoformatting based on ordering.

Thanks again, hopefully, this helps! Please let me know if you have any questions, comments, or concerns.

**Comment by timtebeek** [comment]
Hi @traceyyoshima , thanks for the detailed answer on your side of things! :) That helps to put in perspective why the two cases are not alike. I'd be fine with adding annotations separately for now, and your description here can serve as a reference in case any others come across this limitation. Welcome to close this issue.

**Comment by traceyyoshima** [comment]
@timtebeek, sure thing - sounds good, I appreciate your questions and contributions!
