### ISSUE TITLE
Surface Java annotation attribute default value

### ISSUE THREAD

**Issue by nbruno** [openrewrite/rewrite#2445]
When visiting an annotation I'd like to be able to determine the default value of its attributes. For example, when parsing a method that is annotated with [`@Deprecated`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Deprecated.html), I'd like to know that the default value for the [`since`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Deprecated.html#since()) attribute on the `@Deprecated` annotation is `""` .

Note that this is different from the usage of the annotation and its defined arguments. If a method used

    @Deprecated(since = "1.0.0") 

then the annotation's arguments would have an entry for the 1.0.0 literal.

For this feature request, we are not concerned about the value that the code has used, but the default that is in the definition of the `@Deprecated` annotation. The desire is to surface that the default value for the `since` attribute is `""` when the attribute value isn't specified.

**Comment by nbruno** [comment]
@jkschneider Should this be reopened to address unpacking the values from the annotations attributes?

**Comment by nbruno** [comment]
Reopening to address unpacking the values of the annotation attributes. More context [in Slack](https://app.slack.com/client/T01A842CX4M/C01A843MWG5/thread/C01A843MWG5-1668969397.352799).

**Comment by nbruno** [comment]
@jkschneider Can we reopen this to address unpacking the annotations attributes? More context in [Slack](https://app.slack.com/client/T01A842CX4M/C01A843MWG5/thread/C01A843MWG5-1668969397.352799).

**Comment by jkschneider** [comment]
Thought this was complete in 7.34.0, but we didn't properly unpack the value attribute.

**Comment by timtebeek** [comment]
This has been implemented. `JavaType.Method` now has a `getDefaultValue()` method (marked `@Incubating(since = "7.34.0")`) that returns annotation attribute default values as `List<String>`.

To access defaults from a `J.Annotation`, get the `JavaType.FullyQualified` from the annotation type, iterate its `getMethods()`, and call `getDefaultValue()` on the matching method.

The TypeTable bytecode path handles all value types (strings, primitives, enums, class literals, nested annotations, arrays). Tests exist in `TypeTableTest` and `TypeTableAnnotationSerializationTest`.
