### ISSUE TITLE
[MAVEN] java.lang.IllegalArgumentException: Illegal character in authority at index 7: file://${basedir}/stage

### ISSUE THREAD

**Issue by jdelobel** [openrewrite/rewrite#2510]
Hi,

When I launch the run command, i have the following error multiple times. and the time between the log 

`14:43:58,362 [INFO] org.openrewrite.maven.RewriteRunMojo - Project [modules pom] Resolving Poms...`

and

`14:51:22,409 [INFO] org.openrewrite.maven.RewriteRunMojo - Project [modules pom] Parsing Source Files`

is about 7 minutes left.

More detail:

```
14:43:58,362 [INFO] org.openrewrite.maven.RewriteRunMojo - Project [modules pom] Resolving Poms...
14:47:44,417 [WARNING] org.openrewrite.maven.RewriteRunMojo - Illegal character in authority at index 7: file://${basedir}/stage
14:47:44,417 [WARNING] org.openrewrite.maven.RewriteRunMojo - Illegal character in authority at index 7: file://${basedir}/stage
14:47:44,418 [WARNING] org.openrewrite.maven.RewriteRunMojo - Illegal character in authority at index 7: file://${basedir}/stage
14:48:30,819 [WARNING] org.openrewrite.maven.RewriteRunMojo - Illegal character in authority at index 7: file://${basedir}/stage
14:51:22,409 [INFO] org.openrewrite.maven.RewriteRunMojo - Project [modules pom] Parsing Source Files
14:51:23,476 [INFO] org.openrewrite.maven.RewriteRunMojo - Project [conf] Resolving Poms...
14:51:23,688 [INFO] org.openrewrite.maven.RewriteRunMojo - Project [conf] Parsing Source Files
14:51:24,660 [INFO] org.openrewrite.maven.RewriteRunMojo - Project [domain] Resolving Poms...
14:51:24,839 [INFO] org.openrewrite.maven.RewriteRunMojo - Project [domain] Parsing Source Files
14:51:30,329 [INFO] org.openrewrite.maven.RewriteRunMojo - Project [persistence] Resolving Poms...
14:51:30,540 [INFO] org.openrewrite.maven.RewriteRunMojo - Project [persistence] Parsing Source Files
14:51:35,867 [INFO] org.openrewrite.maven.RewriteRunMojo - Project [wsserver] Resolving Poms...
14:51:36,033 [INFO] org.openrewrite.maven.RewriteRunMojo - Project [wsserver] Parsing Source Files
```
Note: I'm using the version 4.36.0 of rewrite maven plugin. If I upgrade to 4.37.0, I'm stuck indefinitely on `Project [modules pom] Resolving Poms...`
How to fix it?

Thanks,
Julien

**Comment by traceyyoshima** [comment]
@tkvangorder do you recognize what may be happening?

**Comment by tkvangorder** [comment]
It is going to be difficult to track this down without more information.

Rewrite is doing maven pom resolution at this step in his example. If we can scope this problem down to a single pom.xml file (rather than a large, multi-module project), that would be helpful. 

Things to look for : 


What repositories are being defined in the pom.xml? This can include any parents it might have.
What mirrors are in play (from `.m2/settings.xml`)?

I suspect there is a repo (or a mirror for that repo) that results in a timeout but we are still trying that repository for every dependency encountered.

As for the "Illegal character in authority" issue, it looks like we are not replacing a property place holder. @jdelobel Is there a pom.xml in the project that defines `file://${basedir}/stage` ? This could also appears in a transitive dependency's pom.xml file as well.

**Comment by jdelobel** [comment]
Hi @tkvangorder,

When i test it at work, there is no problem. It works fine. The problem occurs only when i work in remote with a corp VPN. I think its an obvious network stuck.
