### ISSUE TITLE
[Recipe] Multiple instanciation and multpile call to visit method

### ISSUE THREAD

**Issue by jdelobel** [openrewrite/rewrite#2519]
Hi,

When i run a custom recipe that override the `visit` method, I  enter in this method **3 times**. 
So i have added a sysout in the constructor and my logs appear **2 times** . 

I don't understand why I have 3 call to visit method but only 2 call on constructor

From my understanding a recipe **has to be instanciated only 1 time**. Is it right?

Thanks.

**Comment by traceyyoshima** [comment]
Hi @jdelobel! It may be a challenge to assess what you see without a stub of a recipe since many things may be happening based on what the recipe is configured to do.

Questions:
- Can you provide a stub of the recipe or more details about what the recipe is doing?
- Are you using `visit`, `visitMethodDeclaration`, or `visitMethodInvocation`?
- What are you doing in the visit that is being invoked?

To get started, I recommend reading the ast-examples [here](https://docs.openrewrite.org/concepts-and-explanations/ast-examples).
And please feel free to join our slack channel to ask any questions you'd like. We're very active in [slack]([Slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA)) and happy to help/answer questions as they arise.

**Comment by jdelobel** [comment]
> * `visit`

Hi @traceyyoshima ;

You can repoduce with an empty recipe:

`````java
public class MyRecipe extends Recipe {

    // logged 2 times
    @JsonCreator
    public MyRecipe() {
        System.out.println("MyRecipe instanciation");

    }

     // logged 3 times
    @Override
    public String getDisplayName() {
        return "MyRecipe ;
    }


    @Override
    protected List<SourceFile> visit(List<SourceFile> before, ExecutionContext ctx) {

        System.out.println("MyRecipe visit");
        return before;
    }
}
````

**Comment by jdelobel** [comment]
FYI I have joined slack community!

**Comment by traceyyoshima** [comment]
> FYI I have joined slack community!

I saw that -- welcome to the community!

> You can repoduce with an empty recipe:

Oh, I see!

For context, so you know and anyone who comes across this:

Generally, I'd recommend overriding `getVisitor()` and providing a visitor that applies to a specific unit of work.

Example:
```java
public class MyRecipe extends Recipe {

    @Override
    public String getDisplayName() {
        return "MyRecipe" ;
    }

    @Override
    public String getDescription() {
        return "Recipe description." ;
    }

    @Override
    protected TreeVisitor<?, ExecutionContext> getVisitor() {
        //Language-specific visitor.
        return new JavaIsoVisitor<ExecutionContext>() {
           // Add applicable overrides of visits here.
        }
    }
}
```

In the visitor, you may use helper utilities like (corresponding to the JavaIsoVisitor in the example) [MethodMatcher](https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/MethodMatcher.java), [AnnotationMatcher](https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/AnnotationMatcher.java), or [TypeUtils](https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java) to ensure the changes are safe to make, and building block recipes like [ChangeType](https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java) that encapsulate complex changes into a single recipe.

In response to your question, it's related to execution cycles and scheduling recipes. What you're seeing is somewhat situational since it may vary depending on how many cycles are configured and how many changes are detected.

You may find documentation on execution cycles [here](https://docs.openrewrite.org/concepts-and-explanations/recipes#execution-cycles).

Please feel free to continue asking more questions as necessary in our slack :)
Does this resolve your issue for now?
