### ISSUE TITLE
Should AddGradleWrapper default to latest version if not provided?

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#2650]
Currently, the `AddGradleWrapper` recipe expects `version` as a mandatory parameter instead of defaulting to the latest version

Gradle supports this natively as running `gradle wrapper` defaults to the latest version if not provided

Additional context: 

I am not sure if this fits this project. 

I understand that it could become a maintenance overhead if the latest version is maintained manually. We could query https://services.gradle.org/distributions/ to find the latest instead of keeping it hard-coded but that means that the recipe would not be be self-contained/work offline.

**Comment by shanman190** [comment]
So this isn't quite accurate. The `gradle wrapper` command defaults to that of the distribution invoking the `wrapper` task. So if you were to run this with a Gradle 7.5 distribution, then you will get a 7.5 wrapper, etc. 

You can see that determination made here:
https://github.com/gradle/gradle/blob/master/subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/GradleVersionResolver.java#L42

As far as the current recipe, it does query the Gradle Services URL to find and validate available versions. This is what makes being able to set the version to `7.x` and get the latest 7.6 release that is available today. You can see that being done here: https://github.com/openrewrite/rewrite/blob/main/rewrite-gradle/src/main/java/org/openrewrite/gradle/util/GradleWrapper.java#L108

The recipe could automatically default to latest though. :)

**Comment by shanman190** [comment]
Also just FYI, `LATEST` means the very latest release published, including integration builds. There is also the virtual `RELEASE` which would really deliver the feature that you want.

**Comment by timtebeek** [comment]
Am I then correct in thinking we could make [AddGradleWrapper.version](https://github.com/openrewrite/rewrite/blob/v7.34.3/rewrite-gradle/src/main/java/org/openrewrite/gradle/AddGradleWrapper.java#L62) default to `RELEASE` and make that parameter optional?
That would seem like a good minimal change, and potentially allow us to run that recipe repeatedly on a schedule.

**Comment by shanman190** [comment]
@timtebeek, you could absolutely schedule this one, but I think you'd probably be wanting to schedule `UpdateGradleWrapper` as there is much more value there. (Same change with history below)

While you could run this one on a schedule, it's only responsible for adding a Gradle wrapper to a repository that doesn't already contain one.

With that said, configuring the version to default to the latest `RELEASE` for `AddGradleWrapper`, I do see as a quality of life improvement albeit a small one insofaras the user would no longer have to specify the single required parameter. Initially, we had set this one up following the common path with the current Gradle command that does both activities. The unfortunate part is that we didn't have a version to act as the default since there is not a Gradle context in place already. So this was the reason why we asked the user to select an initial version as the starting point. I think as yeikel pointed out though, it's reasonable for a user to expect to get the latest release version added to a repository that they execute this recipe upon.

**Comment by timtebeek** [comment]
@shanman190 You're absolutely right, makes more sense to schedule the update recipe rather than this one!

@yeikel would you like to take credit for this small change with a PR? I could do it, but don't want to rob you of the fun. :)
Could be a nice step up to https://github.com/openrewrite/rewrite/issues/2651 as well, as version would then no longer be required, making that one easier.

**Comment by yeikel** [comment]
> So this isn't quite accurate. The `gradle wrapper` command defaults to that of the distribution invoking the `wrapper` task. So if you were to run this with a Gradle 7.5 distribution, then you will get a 7.5 wrapper, etc.
> 
> You can see that determination made here: https://github.com/gradle/gradle/blob/master/subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/GradleVersionResolver.java#L42
> 
> As far as the current recipe, it does query the Gradle Services URL to find and validate available versions. This is what makes being able to set the version to `7.x` and get the latest 7.6 release that is available today. You can see that being done here: https://github.com/openrewrite/rewrite/blob/main/rewrite-gradle/src/main/java/org/openrewrite/gradle/util/GradleWrapper.java#L108
> 
> The recipe could automatically default to `LATEST` though, which is a virtual handle to the latest version that comes back. If you set it to `LATEST`, this behavior is already there. The recipe just expects that you tell it specifically what version to select rather than having a default value specified. :)

I stand corrected. Based on my interpretation of the docs and anecdotal evidence, I assumed it would pick the latest. Thank you for the detailed write-up! 

> @shanman190 You're absolutely right, makes more sense to schedule the update recipe rather than this one!
> 
> @yeikel would you like to take credit for this small change with a PR? I could do it, but don't want to rob you of the fun. :) Could be a nice step up to #2651 as well, as version would then no longer be required, making that one easier.

I should be able to do so. Feel free to assign it to me :)
