### ISSUE TITLE
NoDoubleBraceInitialization sometimes falis to add the initializer contents to the collection

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#2674]
We have found an example where a-double brace collections initialization like:
```java
OTList otList = new OTList() {{ new OTElement(); }};
```
is turned into:
```java
OTList otList = new OTList();
new OTElement();
```

It looks like this is some sort of custom `List` implementation. If a custom collection type like this one cannot be added to through the normal means then this recipe should make no change at all.
If it can be added to as normal, then the result should be:
```java
OtList otList = new OTList();
otList.add(new OTElement());
```

**Comment by kunli2** [comment]
Seems the original code wanted to add an element to the list like this 
```java
OtList otList = new OTList();
otList.add(new OTElement());
```
if so, the original source code should looks like:
```java
OTList otList = new OTList() {{ add(new OTElement()); }};
```
it seems a code bug in the code, for this case, we don't want to transform the code.
### Solution
Check if there are any method invocations (better to limit to methods in the anonymous class ) inside the double brace, if there are no method invocations like `add()`, `push()` to add the initializer contents to the collection, means the intention of code is uncertain, so we don't want to transform this code since it could introduce other warnings.
