### ISSUE TITLE
ArrayIndexOutOfBoundsException from DependencyUseMapNotation 

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite#2805]
Discovered using SAAS to run DependencyUseMapNotation on Default repositories.

The recipe can throw an index out-of-bounds exception.
![Screenshot 2023-02-07 at 12 12 11 PM](https://user-images.githubusercontent.com/16889475/217354538-9a1cb28c-94b9-49f1-8761-ffef4c8f18f6.png)

**Comment by shanman190** [comment]
Since this is on the basic string side, it may be easier to utilize the `DependencyStringNotationConverter` utility clas for parsing the string. This would then make it easier to put the appropriate pieces into their map entries and also help to complete the picture for the remaining string notations (ie. Classifier and extension).
