### ISSUE TITLE
Downgrade usage of instanceof

### ISSUE THREAD

**Issue by AresEkb** [openrewrite/rewrite#2817]
I need to transform instanceof pattern-matching
```
if (obj instanceof String str) {
    return str;
}
```
to a simple instanceof:
```
if (obj instanceof String) {
    String str = (String) obj;
    return str;
}
```

Here is the solution:
```
import org.openrewrite.ExecutionContext;
import org.openrewrite.Recipe;
import org.openrewrite.TreeVisitor;
import org.openrewrite.java.JavaIsoVisitor;
import org.openrewrite.java.JavaTemplate;
import org.openrewrite.java.tree.J.Block;
import org.openrewrite.java.tree.J.Identifier;
import org.openrewrite.java.tree.J.If;
import org.openrewrite.java.tree.J.InstanceOf;

public class InstanceOfRecipe extends Recipe {

    @Override
    public String getDisplayName() {
        return "Downgrade usage of instanceof";
    }

    @Override
    public String getDescription() {
        return "Transforms instanceof pattern-matching to a simple instanceof.";
    }

    @Override
    protected TreeVisitor<?, ExecutionContext> getVisitor() {
        return new InstanceOfVisitor();
    }

    public class InstanceOfVisitor extends JavaIsoVisitor<ExecutionContext> {

        @Override
        public If visitIf(If iff, ExecutionContext p) {
            if (iff.getIfCondition().getTree() instanceof InstanceOf instanceOf && instanceOf.getPattern() != null) {
                if (iff.getThenPart() instanceof Block block) {
                    JavaTemplate template = JavaTemplate
                            .builder(this::getCursor, "Object #{} = #{any()}.class.cast(#{any()})")
                            .build();
                    return iff.withIfCondition(iff.getIfCondition().withTree(instanceOf.withPattern(null)))
                            .withThenPart(block.withTemplate(template, block.getCoordinates().firstStatement(),
                                    ((Identifier) instanceOf.getPattern()).getSimpleName(),
                                    instanceOf.getClazz(),
                                    instanceOf.getExpression()));
                }
            }
            return iff;
        }

    }

}
```

And the test case:
```
import static org.openrewrite.java.Assertions.java;

import org.junit.jupiter.api.Test;
import org.openrewrite.test.RecipeSpec;
import org.openrewrite.test.RewriteTest;

class InstanceOfRecipeTest implements RewriteTest {

    @Override
    public void defaults(RecipeSpec spec) {
        spec.recipe(new InstanceOfRecipe());
    }

    @Test
    void instanceOfIsDowngraded() {
        rewriteRun(
                java(
                        """
                                    package com.example;

                                    class Example {
                                        public String test(Object obj) {
                                            if (obj instanceof String str) {
                                                return str;
                                            }
                                            return null;
                                        }
                                    }
                                """,
                        """
                                    package com.example;

                                    class Example {
                                        public String test(Object obj) {
                                            if (obj instanceof String) {
                                                String str = (String) obj;
                                                return str;
                                            }
                                            return null;
                                        }
                                    }
                                """));
    }

}
```

But it generates the following variable declaration:
```
Object str = String.class.cast(obj);
```
instead of
```
String str = (String) obj;
```
How shoud I fix the recipe to achive it? I tried a lot of variants, all of them throw errors.

**Comment by AresEkb** [comment]
I expected something like this to work:
```
JavaTemplate template = JavaTemplate
        .builder(this::getCursor, "#{any()} #{} = (#{any()}) #{any()}")
        .build();
return iff.withIfCondition(iff.getIfCondition().withTree(instanceOf.withPattern(null)))
        .withThenPart(block.withTemplate(template, block.getCoordinates().firstStatement(),
                instanceOf.getClazz(),
                ((Identifier) instanceOf.getPattern()).getSimpleName(),
                instanceOf.getClazz(),
                instanceOf.getExpression()));
```
But it throws "java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0".

**Comment by timtebeek** [comment]
Hi @AresEkb ; surprising but given your circumstances perhaps understandable recipe suggestion; Would this be something you're looking to contribute? If so it's perhaps easiest to iterate and provide feedback on a draft pull request rather than code snippets in this issue. You can style your contribution after the recipe @knutwannheden added just last week to [do the opposite](https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/cleanup/InstanceOfPatternMatch.java).

**Comment by AresEkb** [comment]
Yes, I'm trying to implement the opposite thing. I need to convert Java 17 code to Java 11. I'm not sure whether it will be helpful for somebody else. However why not. Thanks for idea! I think I'll create a merge request.

But I think I'm too far from the solution for now. Maybe I misunderstand some basic things. Are there any examples of a variable declaration generation? Maybe I should not use JavaTemplate and create it using some explicit constructors instead?

**Comment by timtebeek** [comment]
JavaTemplate is typically preferred since it's more convenient to insert correctly in the surrounding code with the correct type; let me know once you've got a fork branch or draft pull request that I can checkout to potentially help. Although time wise I might need to hand over to my US colleagues. :)

**Comment by knutwannheden** [comment]
@AresEkb In your template you need to use `#{}` rather than `#{any()}` for the class references, since these are not class literals (which have a trailing `.class` like `String.class`) and thus not expressions. So your template should look something like this: `#{} #{} = (#{}) #{any()};`. Please also note the trailing semicolon.

As the actual value for these two template parameters (the first and the third one) you should provide a String. For this you can do use: `instanceOf.getClazz().toString()`. This way you will in the variable declaration end up getting the same reference (qualified or not) as in the original source and thus also don't have to fiddle with the imports.

**Comment by AresEkb** [comment]
Thanks for the suggestion! It works, I created a pull-request https://github.com/openrewrite/rewrite/pull/2828

It works in general, but some of the tests are failed. Maybe one could help to fix it?
