### ISSUE TITLE
Add Gradle Enterprise plugin recipe should adapt to the Gradle version

### ISSUE THREAD

**Issue by alextu** [openrewrite/rewrite#2999]
See https://docs.gradle.com/enterprise/gradle-plugin/#applying_the_plugin:
- Starting from Gradle 6.x, the plugin is applied to the settings.gradle 
- Before Gradle 6.x, the plugin is applied to the root build.gradle

The current recipe always applies the plugin to the settings.gradle, best would be that the recipe detects the Gradle version (not sure yet how easy it is) and applies the pluging conditionnaly to settings.gradle or build.gradle

**Comment by alextu** [comment]
Thanks for the reactivity ! 
I tried the fix on my side, now it seems to apply the plugin to both `settings.gradle` and `build.gradle`, it should be one or the other according to the version, but not both.

**Comment by shanman190** [comment]
@alextu, thanks for bringing this up. I've improved the test cases are part of https://github.com/openrewrite/rewrite/pull/3006 to ensure that it applies correctly as intended by the Gradle documentation.

If you're interested, the issue was that applicability tests weren't adhered to for `doAfterVisit(..)` invocations, so I've switched that around in order to fix your issue.

**Comment by alextu** [comment]
Nice ! Thanks now it's working fine
