### ISSUE TITLE
Gradle AddDependency `onlyIfUsing` fails to detect usage in Groovy

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite#3053]
As [reported by @dauer via Slack](https://rewriteoss.slack.com/archives/C01A843MWG5/p1679569790556479), with a minimal reproduction sample: https://github.com/dauer/openrewrite-gradle-adddependency

In short he as a [conditional `onlyIfUsing` before adding a dependency](https://github.com/dauer/openrewrite-gradle-adddependency/blob/69b5b772aae211b3baf695c08d175d7c46cd89ac/rewrite.yml#L6C9-L11), which should be satisfied in [MyClass.groovy#L6](https://github.com/dauer/openrewrite-gradle-adddependency/blob/main/src/main/groovy/MyClass.groovy#L6), possibly because we only evaluate JavaProjects;
https://github.com/openrewrite/rewrite/blob/2dbfdac6acd3bb09f0b60fbf2da2cebf6f2466ad/rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependency.java#L136-L144

We might be able to replicate his sample in a unit test for AddDependency & onlyIfUsing, similar to this existing test:
https://github.com/openrewrite/rewrite/blob/2dbfdac6acd3bb09f0b60fbf2da2cebf6f2466ad/rewrite-gradle/src/test/java/org/openrewrite/gradle/AddDependencyTest.java#L70-L110

That currently uses https://github.com/openrewrite/rewrite/blob/2dbfdac6acd3bb09f0b60fbf2da2cebf6f2466ad/rewrite-java/src/main/java/org/openrewrite/java/Assertions.java#L142-L144

For which [there's not yet an equivalent in the Groovy Assertions](https://github.com/openrewrite/rewrite/blob/main/rewrite-groovy/src/main/java/org/openrewrite/groovy/Assertions.java#L142).

**Comment by shanman190** [comment]
Ok, I've found the issue in particular that is causing this to fail...

In particular, there is no `JavaSourceSet` marker on the groovy source files. As a result, this prevents identification of which source set the class belongs to leads to an early exit for the `AddDependency` recipe.

The reason for there not being any `JavaSourceSet` marker is because:
1) Unlike the `JavaParser`, the `GroovyParser` doesn't add a default `SourceSet` to any files that it parses. 
2) The `rewrite-gradle-plugin` doesn't add a `SourceSet` marker while it's doing the parsing of the Gradle Groovy source set.

So far the `GroovyParser` has really only been used to parse `*.gradle` files. As an interesting trait though, it does bring up the issue of whether the `JavaParser` (or `KotlinParser`) should be adding it's own `SourceSet` or if that should be driven from the outside. To illustrate this more exactly, with the `GroovyParser` it's parsing `*.gradle` files that are not part of a Gradle source set, so it makes sense for there to be no `JavaSourceSet` marker as the file is not part of a source set. For `*.gradle.kts` (once we get these parsing), there would likely be the same desire. Similarly, there is a nearly identical case for `*.java` files as well that presents in the form of the maven-wrapper's `MavenWrapperDownloader.java` file which as well would not be part of a source set.

All this is to say, that to fix this we probably need to rethink how `SourceSet` marker management should be performed and where those tasks should take place.
