### ISSUE TITLE
AddImport doesn't allow setting Layout

### ISSUE THREAD

**Issue by blakesmith** [openrewrite/rewrite#31]
Hi there!

I'm using the `AddImport` java refactor visitor in a library refactoring I'm building. `AddImport` delegates to `OrderImports` in order to reorder the imports. 

A few things:

1. Would you all take a patch that adds a setting on `AddImport` to disable reordering imports after adding an import (just a setter on the `AddImport` object)?
2. If we do want to order imports, should the `Layout` is be configurable from the `AddImport` call? Our company style prefers explict imports, rather than wildcarded imports, so we'd prefer to be able to disable wildcard importing if we do end up wanting to re-order imports.

Let me know what you think!

Thanks for openrewrite, we're just starting to use it for some large-scale library refactorings, and are enjoying it so far!

**Comment by jkschneider** [comment]
Hi @blakesmith. It's always useful when launching OSS products like this to chat in detail with the early adopters, so would love to learn more about what you're doing on [Slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-h7bqtyxx-nBjZPdqc9fXBugZKnEOlog) or just block a bit of time on [calendar](https://jonkschneider.youcanbook.me/). To import layouts...

Let's address (2) first and see if there's still a desire for (1) after.

Import layouts are configured as a [style](https://docs.openrewrite.org/java/parsing-java-code#import-layout-style) that are added to the parser. So if you are using the Maven plugin, you can define the style in YML and activate it with `<activeStyles>`. If you are building a parser on your own, you can add it to the parser builder.

We actually store import layout style on the root AST element (`J.CompilationUnit`) for a couple reasons:
1. Since so many visitors indirectly add or remove an import, we didn't want to have to leak import layout configuration through all of those visitors.
2. We're building toward a future where we can refactor en masse across ASTs from multiple repositories, which may have different styles (like import layouts). By storing styles on the AST, you can configure a set of visitors to operate on all of those sources and have the results look idiomatic for each project.

Again, super interested in what you're working on. Let me know what you think!

**Comment by blakesmith** [comment]
@jkschneider Oh, very cool. Is that documentation new? I've been just going through source code to figure things out for the time being. Very slick looking documentation. 

None of this is through maven, but I will look at setting this `ImportStyle` programmatically on the `J.CompilationUnit`.

I added some time to your calendar on Monday, and would love to show you what I'm working on, and get your ideas and input! Hopefully it will be helpful to both of us.

Thanks again!
