### ISSUE TITLE
`/*__TEMPLATE_STOP__*/` shows when going from rewrite-recipe-bom 1.17.0 -> 1.18.1

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite#3102]
This is an issue on behalf of cucumber-jvm-migration; when [upgrading the rewrite-recipe-bom there to 1.18.1](https://github.com/cucumber/cucumber-jvm-migration/pull/6) we now see failures in a number of different tests.
![image](https://user-images.githubusercontent.com/1027334/230971235-828b0db6-755a-42f1-92ed-1251a9ba3db5.png)

As an example, in the bottom test we assert that the following is correctly converted:
```java
package com.example.app;

import io.cucumber.java8.En;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class CalculatorStepDefinitions implements En {
    private RpnCalculator calc;

    public CalculatorStepDefinitions() {
        Given("a calculator I just turned on", () -> {
            calc = new RpnCalculator();
        });

        When("I add {int} and {int}", (Integer arg1, Integer arg2) -> {
            calc.push(arg1);
            calc.push(arg2);
            calc.push("+");
        });

        Then("the result is {double}", (Double expected) -> assertEquals(expected, calc.value()));
    }

    static class RpnCalculator {
        void push(Object string) {
        }

        public Double value() {
            return Double.NaN;
        }
    }
}
```

Which still mostly works, with the one exception.
![image](https://user-images.githubusercontent.com/1027334/230971826-beeea91c-057b-41b1-9a1b-e045b835c124.png)

The corresponding replacement is constructed here:
https://github.com/cucumber/cucumber-jvm-migration/blob/c7ecb188a335c9d2de30f6629cfb4fa9cd92763c/src/main/java/io/cucumber/migration/CucumberJava8StepDefinitionToCucumberJava.java#L116-L124

This used to work previously, and up to recently was included in rewrite-testing-frameworks. Unfortunately it's since been split off, which caused this delay in finding the issue.

**Comment by kunli2** [comment]
@timtebeek is the `cucumber-jvm-migration` our owned project? I tried to pull up a PR to add some tests but it says I don't have permission to create PR.

**Comment by timtebeek** [comment]
The missing semicolons were just added in https://github.com/cucumber/cucumber-jvm-migration/pull/6/commits/a254bd972793d2614636d554218ef40e1996ece3, which indeed seems to have resolved the template stop issues, thanks!

A new issue though is that the double block braces are no longer removed from:
```java
      @Given("{int} plus {int}")
      public void int_plus_int(Integer a, Integer b) {
          {
  
              // Lambda body comment
              int c = a + b;
          }
      }
```
Despite the [explicit call to remove unneeded blocks](https://github.com/cucumber/cucumber-jvm-migration/blob/a254bd972793d2614636d554218ef40e1996ece3/src/main/java/io/cucumber/migration/CucumberJava8ClassVisitor.java#L57-L58).

If I introduce the semicolons on the `main` branch with the older rewrite `1.17.0` then the unneeded block is still correctly removed, so the issue is new as of `1.18.1`.

Any suggestions how to resolve that final issue such that the PR can be merged?

**Comment by knutwannheden** [comment]
The issue with the non-inlined block statement is due to a change in the `RemoveUnneededBlock` recipe: In https://github.com/openrewrite/rewrite/commit/4cc248cd0f4b063d9a52f38437163cff8afd20d3 I modified it so that it no longer inlines nested blocks which contain variable declarations, as these could conflict with variables which are declared in subsequent statements in the outer block. It turns out that this was overly defensive: A nested block can always be inlined when it is the last statement in the outer block.

For the Cucumber recipes inlining the last nested block would solve the problem, as here the outer block is the "implicit" block formed by the method body and the inner block is the body of a lambda (for the case when that is an explicit block and not a single statement) and with the Java template being used the outer block only ever contains one statement. I have implemented this improvement in https://github.com/openrewrite/rewrite/commit/0c28f4bae0ae291373534ba1bcbdbd660c86a180 and https://github.com/openrewrite/rewrite/commit/84addc4b995a3d0e3ade6156536c13d04b65d44b.
