### ISSUE TITLE
Add ratcheting functionality 

### ISSUE THREAD

**Issue by gdupontf** [openrewrite/rewrite#3335]
## What problem are you trying to solve?

Implement incremental adoption of refactoring rules.

## Describe the solution you'd like

Given a target list of refactorings, such feature would pick between at least 2 configurable modes :

* Pick a single refactoring from the target list, add it to the configuration and run check/run as normal.
* Pick refactorings in order of declaration and run them one by one until one produces a build error.

You would then commit the changed recipe file alongside the actual refactorings.

## Have you considered any alternatives or workarounds?

You can painstakingly implement this manually using your CI/CD of choice, but nothing as self-contained as something like this would be.

## Additional context

I'm not overly familiar with the core API so maybe this could be implemented as a recipe.

## Are you interested in [contributing this feature to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#new-features)?

I can try in my spare time. I would hesitate if it touches on core libraries but if it fits as a recipe it may be easier onboarding for me.

**Comment by gdupontf** [comment]
With a little bit more thinking on this I would say it can also be implemented as marking recipes as capable of acting on single files. This would be a matter of supporting a list of files as input from both SCM and user-provided sources.

**Comment by timtebeek** [comment]
Hi @gdupontf ! Interesting suggestion! Could you tell us a bit more why you're looking for an incremental approach, and how OpenRewrite factors in?

And just to be clear; did you intend to open this as a feature request for OpenRewrite? Since the core of OpenRewrite itself currently does not integrate with SCM or CI/CD, I thought perhaps this could be a better fit for the Moderne platform. We track requests for the Moderne platform separately via https://github.com/moderneinc/support-app and customer specific support-repositories, if that helps.

Via the Moderne platform we already allow you to [select and compose recipes in the builder](https://docs.moderne.io/user-documentation/recipe-builder), which you can then selectively, or altogether run against one or multiple repositories. This produces previews of the changes that would be applied, which you can then optionally convert into direct commits or pull requests. From the preview page we also have a Validate button which will allow you to verify these changes before creating a commit. For all of this we also offer an API, in case you're looking to integrate this with other systems on your end. This way you're able to roll out and apply changes at your own pace already, if you're so inclined.

The benefit of the platform versus OpenRewrite is that we allow you to run these recipes much quicker, since the Lossless Semantic Tree is already available, as opposed to having to recreate that before every run with OpenRewrite. The platform also offers everything to run these recipes at scale, and follow through with commits and pull requests to track your changes.

Does that help to achieve your goals already? Happy to go over the options with you via any channel, either public or private.

**Comment by gdupontf** [comment]
I understand, this conflicts with your commercial offering.
