### ISSUE TITLE
How to activate a recipe with parameter in programtic way?

### ISSUE THREAD

**Issue by i059917** [openrewrite/rewrite#3463]
## What problem are you trying to solve?
Hello, I am new and at beginning to learn open-rewrite, my project is not based on gradle or maven, but I see open-rewrite also support run recipes in programtic way here:
https://docs.openrewrite.org/running-recipes/running-rewrite-without-build-tool-plugins
Here I would like to activate org.openrewrite.java.RemoveAnnotation recipe by invoke environment.activate(), RemoveAnnotation recipe requires a ' annotationPattern' paramenter. It seems that activate() mehtod of Environment class only support accepting recipe class name string as input.

## Describe the solution you'd like
I would to have recipe instance rahter than recipe name String to be activated like this:
```
Environment env = Environment.builder().scanRuntimeClasspath().build();

Recipe recipe = new org.openrewirte.java.RemoveAnnotation(${annotation});

env.activateRecipes(recipe);
```

**Comment by joanvr** [comment]
Recipe parameters in recipes are usually loaded through a declarative recipe yml file, as you can see here: [running-a-recipe-with-configuration-parameters](https://docs.openrewrite.org/running-recipes/running-rewrite-on-a-maven-project-without-modifying-the-build#running-a-recipe-with-configuration-parameters). You can add a yml file in your classpath at `META-INF.rewrite` to do so.

Recipes are loaded via an string, because the Environment and activateRecipes takes care of the classpath/dependencies. If you want to take care of the dependencies yourself, you can instantiate the recipes as you are showing on your snippet and use them directly. Some recipes have all args constructors and thats how they are instantiated in the tests actually.

Another solution would be to get the "non parametrized" recipe from the environment and then use reflection (jackson for example) to populate the recipe parameters.

**Comment by i059917** [comment]
@joanvr thank you, I made yml file in my classpath, and recipe can be loaded now. 

But org.openrewrite.java.RemoveAnnotation recipe doesn't work as my expectation. Here I would remove an deprecated Spring annotation @Required from my source code, but seems open-rewrite AnnotationMatcher is not able to determine the type of the annotation(it determine @Required annotation as type 'Unknown'... see screen shot), then the source code get no change due to no annotation matched.

Any hints here? Maybe I need create a separated github issue for this?

My yml file:
`
---
type: specs.openrewrite.org/v1beta/recipe
name: com.poc.rewrite.RemoveDeprecatedAnnotation
recipeList:
  - org.openrewrite.java.RemoveAnnotation:
      annotationPattern: '@org.springframework.beans.factory.annotation.Required'
`

My source code:
`
import org.springframework.beans.factory.annotation.Required;

public class MyClass {

    private String name;

    @Required
    public void setName(String name) {
        this.name = name;
    }
}
`

Debug screen shot:
<img width="1139" alt="image" src="https://github.com/openrewrite/rewrite/assets/9570835/66291437-d895-4da1-a597-6414c17aac1c">

**Comment by timtebeek** [comment]
Hi @i059917 ! If you see type `Unknown` on tree elements that usually means the respective types are not available on the classpath. What classpath entries are you passing into the parser? Those would have to include some spring dependencies before those types can be resolved.

It's not an easy undertaking to bypass the Maven and Gradle plugins and how they set up the parsers and classpath for you. You might want to [look at the OmniParser recently added to rewrite-all](https://github.com/openrewrite/rewrite-all/blob/main/src/main/java/org/openrewrite/OmniParser.java), and see if that allows you to more easily set up every thing you need to parse your project.

Out of curiosity: what build system are you using? Since we have support for Maven and Gradle through OSS build plugins already, and support for Bazel through the Moderne platform. I'm wondering if either of those options could work for you.

**Comment by i059917** [comment]
@timtebeek Thanks for the hint. Yes, I didn't make that classpath correctly, now it works after I fixed it.  My project is bascially Ant build based and dependencies are copied at customized path. Now I understand more of how open-rewrite work. If your project is based on Maven or Gradle and you trigger open-rewrite from 'mvnw' or 'gradlew', classes of dependecies will be there by default. But if you are without maven or gradle build system, you have to manage that path list correctly.

**Comment by timtebeek** [comment]
Thanks for reporting back here @i059917 ! Glad to hear fixing the classpath issues got you further. If you have anything you can share about support for Ant we'd love to hear ; We hadn't added explicit support for that yet, but if what you're building can be generalized to other Ant projects that could be interesting for us to evaluate too.

**Comment by i059917** [comment]
Hi @timtebeek thanks. My project is based on Ant, it is not in a typical standard ant project structure. If open-rewrite could be triggered by provide some customized properties like _ant openrewrite -Drecipe={xxx} -Dclasspath={xxx} -Dsrc={xxx}_, I think it is possible that my project adapt to use in that way.
I think it is good for now in my project starting in programatical way, I am just wondering if there could more tutorial materials for different code refactoring case, maybe it is due to I'm new here, the feeling to me is this is a powerful framework, but sometimes need to know more about how it works in details. :)

**Comment by timtebeek** [comment]
hi @i059917 ; not quite sure what kind of tutorial materials you're looking for, so I'll provide a few links and you're always [welcome in our Slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA) to ask more questions if that helps.

We have a number of popular recipe guides, that you might want to evaluate for your project:
https://docs.openrewrite.org/running-recipes/popular-recipe-guides

When people get started with Moderne we recommend they start with recipes in this order:
https://docs.moderne.io/administrator-documentation/proof-of-value#recipes-to-run
You can run these same recipes through OpenRewrite; the link is just to give you an idea of what to run first.

If you want write your own recipes then this is a good starting point: https://docs.openrewrite.org/authoring-recipes

Past that it's probably easiest to chat in Slack, as then we can go a bit more in depth without any delay in responding.
