### ISSUE TITLE
Test adding newline on generated plain text?

### ISSUE THREAD

**Issue by sghill** [openrewrite/rewrite#3491]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v8.4.0-SNAPSHOT
- rewrite-jenkins [bugfix/generate-codeowners-with-newline](https://github.com/openrewrite/rewrite-jenkins/tree/bugfix/generate-codeowners-with-newline) branch

## How are you running OpenRewrite?

Through moderne.io and building the rewrite-jenkins project with Gradle and RewriteTest.

## What is the smallest, simplest way to reproduce the problem?

I have a failing test [here](https://github.com/openrewrite/rewrite-jenkins/blob/d2f3443fee868851c1eff1d04cca86a2ce43b587/src/test/java/org/openrewrite/jenkins/github/AddTeamToCodeownersTest.java#L57-L69).

```java
@Test
@DocumentExample
void shouldAddFileIfMissing() {
    rewriteRun(
      pomXml(POM),
      text(null,
        """
        * @jenkinsci/sample-plugin-developer
        """,
        s -> s.path(".github/CODEOWNERS").noTrim()
      )
    );
}
```

## What did you expect to see?
I expected that [generating my file](https://github.com/openrewrite/rewrite-jenkins/blob/bugfix/generate-codeowners-with-newline/src/main/java/org/openrewrite/jenkins/github/AddTeamToCodeowners.java#L87) with a `\n` on the end would create the file with a blank trailing line.

## What did you see instead?
My test fails with no newline at the end

```
[Unexpected result in ".github/CODEOWNERS"] 
expected: 
  "* @jenkinsci/sample-plugin-developers
  "
 but was: 
  "* @jenkinsci/sample-plugin-developers"
```

## What is the full stack trace of any errors you encountered?
No stacktrace

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Yes

**Comment by timtebeek** [comment]
Hmm; traced this through with the debugger with the following test.
```java
@Test
void hasCreatedFileWithTrailingNewline() {
    rewriteRun(
      spec -> spec.recipe(new CreateTextFile("foo\n", ".github/CODEOWNERS", false)),
      text(
        null,
        "foo\n",
        spec -> spec.path(".github/CODEOWNERS").noTrim()
      )
    );
}
```

Looks like this might (mostly) be an issue with RewriteTest
https://github.com/openrewrite/rewrite/blob/889393587499680f0ff9abfef13bc97af77729b4/rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java#L385-L388

Notice how we trim the actual expected output no matter the value of `sourceSpec.noTrim`. If we instead conditionally trim after too, then the test starts to pass.
```diff
- String actual = result.getAfter().printAll(out.clone()).trim();
+ String actual = result.getAfter().printAll(out.clone());
+ actual = sourceSpec.noTrim ? actual : actual.trim();
  String expected = sourceSpec.noTrim ?
          sourceSpec.after.apply(actual) :
          trimIndentPreserveCRLF(sourceSpec.after.apply(actual));
```
We seem not to use `noTrim` in a lot of cases, so that seems like reasonably safe thing to do to fix the test.

But then the issue you were having did not limit itself to tests only right? I'm not seeing a direct parallel to the `.trim()` call outside if RewriteTest. 🤔

**Comment by timtebeek** [comment]
Created https://github.com/openrewrite/rewrite/pull/3492 for the test issue; waiting to hear if we need a fix outside of tests too.

**Comment by sghill** [comment]
The fix for the test issue was all that was needed. Thanks Tim!
