### ISSUE TITLE
Problem parsing unknown Javadoc tag

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite#3750]
When Javadoc contains unknown tags as `{@return}` in the following test, the parser ends up with a parse-to-print failure:
```java
    @Test
    void javadocUnknownTag() {
        rewriteRun(
          java(
            """
              interface Test {
              	/**
              	 * {@return 42}
              	 */
              	int foo();
              }
              """
          )
        );
    }
```

**Comment by traceyyoshima** [comment]
I looked at this, and the `@return` is parsed by the JavaDocVisitor, but it doesn't expect the tag to be wrapped by `{}`. The unexpected characters cause an issue with the cursor position, which leads to a non-idempotent print.

**Comment by TheMarvelFan** [comment]
Hi,
From what i understand, this issue can be resolved by modifying the JavaDocVisitor to ignore the wrapping of curly braces (only?) and not changing anything else in the file.
Please feel free to add anything that I may have overlooked. I would like to start working on this as soon as I get a reply.

**Comment by traceyyoshima** [comment]
Hi @TheMarvelFan! Several cases exist, two of which will fail:

- `@return Id` parses and prints fine since it matches the expected Java doc syntax.
- `@return Id}` parses and prints fine since it fits into the Java doc syntax.
- `{@return Id` and `{@return Id}` fail to parse and print.

The issue's root is the `sourceBefore` in visitReturn does not expect a leading `{`, and the DocTree node contains the `{` character. So, detecting the unexpected character is simple, but we'll need a marker or something to inform the printer to add `{` when the character exists.

**Comment by TheMarvelFan** [comment]
@traceyyoshima @timtebeek 
Thanks for letting me work on this issue. I appreciate your patience throughout the process as I tend to make mistakes.
