### ISSUE TITLE
Changes are reported to have been made by mulitple recipes but not change is actually made

### ISSUE THREAD

**Issue by blipper** [openrewrite/rewrite#4402]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite 8.28.1

## How are you running OpenRewrite?
Custom Gradle Plugin 

## What is the smallest, simplest way to reproduce the problem?

Running the scanner below I see this
```
Validating active recipes
Scanning sources in project :
Using active styles []
Scanned 36 Java sources in :/main
Scanned 24 Java sources in :/test
All sources parsed, running active recipes: org.openrewrite.staticanalysis.FinalizeLocalVariables
Changes have been made to src/main/java/com/amazon/javelinprimingcontextservice/cache/dao/MergingCacheDao.java by:
    org.openrewrite.staticanalysis.FinalizeLocalVariables
Changes have been made to src/main/java/com/amazon/javelinprimingcontextservice/cache/client/PubSubHandler.java by:
    org.openrewrite.staticanalysis.FinalizeLocalVariables
Changes have been made to src/test/java/com/amazon/javelinprimingcontextservice/cache/client/RedisElastiCacheClientLuaTest.java by:
    org.openrewrite.staticanalysis.FinalizeLocalVariables
Please review and commit the results.
Estimate time saved: 15m
```

But run `git status`

```
dev-dsk-mnr-1e-4bc3dc7c % git status
On branch mainline
Your branch is ahead of 'origin/mainline' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
```

Haven't been able to reproduce what triggers it though.  It impacts multiple recipes

## What did you expect to see?

Either
A) `git status`  should show changed files
B) Openrewrite shouldn't report any issues

## What did you see instead?

Openrewrite reports a change BUT `git status` doesnt' show any changes.

## Are you interested in [contributing a fix to OpenRewrite]
Yes

**Comment by timtebeek** [comment]
Thanks for the report @blipper ! Had a brief look at this particular recipe, but also can't work out why that would report to make a change without any visible changes; Is there anything in those three files that you could pull over into a unit test that replicates the issue?

As you'll know by now we always try to replicate issues with a unit test like this one; ideally fixed issues instead of counteracting their effects.
https://github.com/openrewrite/rewrite-static-analysis/blob/692b242b9756b0b2290f56f8a05bfee0d95d5303/src/test/java/org/openrewrite/staticanalysis/NoFinalizedLocalVariablesTest.java#L34-L71

**Comment by blipper** [comment]
Sorry. You can close this.  This is a bug with JGit :(
