### ISSUE TITLE
NoValueOfOnStringType cannot be remove 

### ISSUE THREAD

**Issue by HelloDhero** [openrewrite/rewrite#4477]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v8.34.0
- Maven/Gradle plugin v5.39.2

## What is the smallest, simplest way to reproduce the problem?

```java
class A {
    // select from db
    List<Map<String,String>> selectFromDb();
}
class B {
   public void test() {
       List<Map<String,String>> selectFromDb= new A().selectFromDb();
       for(Map<String,String> map:selectFromDb){
           String a = String.valueOf(map.get("key"));
       }
   }
}
```
the results of selectFromDb may not `List<Map<String,String>>`, the item value of map may be other type (Long、Date...), in this case ,remove `String.valueOf` while cause ClassCastException in runtime

**Comment by timtebeek** [comment]
hi! That's surprising; do you mean to say that `selectFromDb()` could return a `List<Map<String,Object>>` as opposed to `List<Map<String,String>>` ? I guess that's _possible_ with erasure, but from looking at the source code there'd be no way to tell, and it'd be unexpected based on the declared generics.

I'd lean towards saying the recipe is doing what it should here based on the code we see; any runtime differences would be due to a very unexpected return from `selectFromDb()` that's perhaps best checked separately.

Or did I misunderstand somehow?

**Comment by HelloDhero** [comment]
yes , So what I want to say is that this is a risky change

**Comment by knutwannheden** [comment]
If the map really can end up containing non-String values you should change the type to Map<String, Object>.
