### ISSUE TITLE
maybeAddImport is not working properly

### ISSUE THREAD

**Issue by Guseyn** [openrewrite/rewrite#48]
As far as I understand `maybeAddImport` adds imports only if it's really needed unlike simple `addImport`. But in this example: https://docs.openrewrite.org/java/refactoring-java-source-code/addfield `maybeAddImport` actually does not add import `org.slf4j.LoggerFactory`, although it's need to be added since it's missing in the original code.

**Comment by sambsnyd** [comment]
@Guseyn there's a bug in the sample for `AddField`. I've fixed the docs accordingly in [this commit](https://github.com/openrewrite/rewrite-docs/commit/3d95c94d39bc6a095f4438d528c3864eb4782bb4).

There are two reasons `maybeAddImport()` wasn't adding an import in that sample:

1. At the time it ran the new field hadn't been added yet. `AbstractRefactorVisitor.andThen()` schedules the provided visitor to be executed immediately after the current visitor. So the `maybeAddImport()` actually runs before the `AddField()` visitor creates the field. 
2. Even if the ordering issue is fixed, `maybeAddImport()` wouldn't add the import because the `LoggerFactory` in the field initialization expression isn't type-attributed. It doesn't know that symbol is referring to `org.slf4j.LoggerFactory` so it still thinks there are no occurrences of `org.slf4j.LoggerFactory` to add an import for. 

#2 is a consequence of `AddField` accepting the initialization expression as a String, rather than a type-attributed AST. This is for convenience, but can have subtle consequences like it did in this case.

Take a look at the updated docs for `AddField` and let me know if that makes sense.

**Comment by sambsnyd** [comment]
@Guseyn heads up I've filed issue https://github.com/openrewrite/rewrite/issues/49 to update AddField's API to make it easier to use without making the mistake that sample made. Thanks again for pointing this out.
