### ISSUE TITLE
rewrite-java-security is not available anymore

### ISSUE THREAD

**Issue by Bananeweizen** [openrewrite/rewrite#4800]
The previously public repository rewrite-java-security is not publicly available anymore. I'm not sure if that was on purpose, if it was renamed, or whether that was an accident. It's still referenced from the docs repository and from the recipe catalog, so I assume this was not intended. 1ab8577f2895b178aafa265168806548762295f1 is the last commit that I have in my local clone.

**Comment by timtebeek** [comment]
hi @Bananeweizen ; thanks for reaching out! This was intentional, and we'll make that clearer from the docs:
- https://github.com/openrewrite/rewrite-recipe-markdown-generator/issues/147

For now you can see an overview of the various recipe modules and their licenses on this page:
https://docs.openrewrite.org/licensing/repository-licensing

This page shows an overview of individual Moderne recipes, in case you were missing any others:
https://docs.openrewrite.org/reference/moderne-recipes

I hope that answers the immediate question you had about unavailability. You can read more about the reasoning here:
- https://github.com/commonhaus/foundation/pull/218

**Comment by Bananeweizen** [comment]
Sorry, but I can't see how not participating in the commonhaus project would lead to a necessity of restricting the licenses of a major part of the OpenRewrite code. I'm deeply disappointed, since I have contributed to several of the repositories that are no longer open source.

**Comment by JLLeitschuh** [comment]
I've raised these concerns in Slack here:

https://rewriteoss.slack.com/archives/C01A843MWG5/p1735228710998069

More to come

**Comment by ljharb** [comment]
@timtebeek without a CLA, relicensing isn’t legal without explicit permission from all contributors.

**Comment by JLLeitschuh** [comment]
From the thread in slack:

<img width="1728" alt="Screenshot 2024-12-26 at 12 44 42 PM" src="https://github.com/user-attachments/assets/cffbba10-4077-460e-a0de-c1b0ca5d7117" />
<img width="1728" alt="Screenshot 2024-12-26 at 12 45 04 PM" src="https://github.com/user-attachments/assets/668661be-cf8b-473d-861a-0fa069773eef" />

**Comment by JLLeitschuh** [comment]
It looks like the decision to make this change was made two weeks ago: https://github.com/moderneinc/moderne-docs/commit/ccd2adad96d71e3b5eed1c24e1fd30987b20de8c#diff-450920303cec650913d28686228afb4665cd010db8f5e0f79d607e8586477f07R11-R12
