### ISSUE TITLE
Java11 parser assertion error: declaringType is null in Java11ParserVisitor#methodType

### ISSUE THREAD

**Issue by mbruggmann** [openrewrite/rewrite#548]
👋🏻

We have been toying around with rewriting some of our Java codebases, and came across files that don't parse in `rewrite-java-11`. Trying to reproduce the issue, this seems to be a smaller test file that doesn't parse for me on v7.4.0:
```java
package com.company.pkg;

import java.util.concurrent.CompletableFuture;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import com.company.pkg.UnknownClass;

public class ReproduceParserIssue {

  public static void main(String[] args) {
    CompletableFuture.supplyAsync(
        () -> {
          return Stream.empty()
              .map(UnknownClass::valueOf)  // <-- this appears to be the problematic method reference 
              .collect(Collectors.toList());
        });
  }
}
```

For example in a testcase like this:
```java
final JavaParser javaParser = JavaParser.fromJavaVersion().build();
final String content = loadTestFileFromAbove();

final List<CompilationUnit> compilationUnits = javaParser.parse(content);
assertEquals(1, compilationUnits.size()); // <-- actually there are 0 compilation units because of the assertion
```

Had a quick look at the code but it's hard for me to say what is happening here without a solid understanding of the internals. Any ideas?

**Comment by jkschneider** [comment]
Thanks for the detailed report @mbruggmann. As you suggested in the title, the parser is encountering a type that under normal compilation is probably on the classpath but isn't in this case. d27d489 fixes the situation when there is a `null` declaringType, but I would expect there can be other consequences of not having the correct classpath.

* Parsing times can be considerably slower
* Things that you expect to get refactored won't because of missing type attribution.

We've found it sometimes hard to try to write offline parsing that determines the classpath independently of the build tool (Maven or Gradle). Hope this helps!

**Comment by mbruggmann** [comment]
Makes sense. We should probably have another look at how we construct the classpath. In any case, thanks for following up so quickly 🎉
